# Generated by Django 5.1.2 on 2024-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('weld_temperature', models.FloatField()),
                ('weld_current', models.FloatField()),
                ('weld_voltage', models.FloatField()),
                ('weld_time', models.IntegerField()),
                ('pressure_applied', models.FloatField()),
                ('arm_position_x', models.FloatField()),
                ('arm_position_y', models.FloatField()),
                ('arm_position_z', models.FloatField()),
                ('wire_feed_rate', models.FloatField()),
                ('gas_flow_rate', models.FloatField()),
                ('weld_strength_estimate', models.FloatField()),
                ('vibration_level', models.FloatField()),
                ('power_consumption', models.FloatField()),
            ],
        ),
    ]
