# Generated by Django 5.0.3 on 2024-10-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50, unique=True)),
                ('machine_type', models.CharField(choices=[('WELDING', 'Welding Robot'), ('STAMPING', 'Stamping Press'), ('PAINTING', 'Painting Robot'), ('AGV', 'AGV'), ('CNC', 'CNC Machine'), ('LEAK_TEST', 'Leak Test Machine')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('webhook_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='webhook_handler.machine')),
            ],
        ),
        migrations.DeleteModel(
            name='MachineData',
        ),
        migrations.AddField(
            model_name='latestsensordata',
            name='machine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_data', to='webhook_handler.machine'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['machine', '-timestamp'], name='webhook_han_machine_69d214_idx'),
        ),
    ]
