# Generated by Django 5.1.2 on 2024-10-19 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0002_latestsensordata_machine_sensordata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('working', 'Working'), ('free', 'Free'), ('not_at_work', 'Not at Work')], default='free', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('report', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('repaire', 'repaire'), ('maintenance', 'Maintenance'), ('change pies', 'changepies')], default='working', max_length=12)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webhook_handler.machine')),
                ('taskdoneby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigned', to='webhook_handler.maintenanceprofile')),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceprofile',
            name='assigned_tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doing', to='webhook_handler.task'),
        ),
    ]
