# Generated by Django 5.1.2 on 2024-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0002_latestsensordata_machine_sensordata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='webhook_url',
            field=models.URLField(),
        ),
    ]
