# Generated by Django 5.1.2 on 2024-10-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0003_maintenanceprofile_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceprofile',
            name='assigned_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doing', to='webhook_handler.task'),
        ),
    ]
