# Generated by Django 5.1.2 on 2024-10-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0003_alter_machine_webhook_url'),
        ('webhook_handler', '0004_alter_maintenanceprofile_assigned_tasks'),
    ]

    operations = [
    ]
