# Generated by Django 5.1.2 on 2024-10-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0005_merge_20241019_1412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('working', 'Working'), ('free', 'Free'), ('not_at_work', 'Not at Work')], default='free', max_length=12)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('assigned_tasks', models.ManyToManyField(blank=True, related_name='agents', to='webhook_handler.task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
